"""포렌식 가이드 시스템

1. /tools/forensic-paths — 레지스트리 핵심 경로 카탈로그
2. /tools/beginner       — 초보자 가이드 (시나리오 기반)
3. /tools/glossary       — 용어집
"""
from flask import request, render_template
from monitor.views.tools import bp


# ════════════════════════════════════════════════════════════════
# 1. 포렌식 핵심 경로 (레지스트리·파일시스템)
# ════════════════════════════════════════════════════════════════
_FORENSIC_PATHS = [
    # ───── SAM 하이브 ─────
    {'hive':'SAM', 'category':'계정 정보', 'severity':'high',
     'path':'SAM\\Domains\\Account\\Users\\Names\\',
     'desc':'로컬 사용자 계정 이름 목록. 각 하위키 이름이 계정명.',
     'check':['계정 목록 전체','기본 RID 외 임의 추가 계정 의심','이름이 공백/특수문자인 숨겨진 계정']},
    {'hive':'SAM', 'category':'계정 정보', 'severity':'high',
     'path':'SAM\\Domains\\Account\\Users\\000001F4\\F',
     'desc':'Administrator(RID 500) 계정의 F 바이너리: LastLogon·암호변경·계정만료·ACB 플래그',
     'check':['마지막 로그온 시각','암호 마지막 변경','비활성/일반계정 플래그','로그온 실패 횟수']},
    {'hive':'SAM', 'category':'계정 정보', 'severity':'high',
     'path':'SAM\\Domains\\Account\\Users\\000001F4\\V',
     'desc':'Administrator V 바이너리: 사용자명·전체이름·홈디렉터리·LM/NT 해시',
     'check':['계정명 (UTF-16)','전체 이름','홈 디렉터리','패스워드 해시 (Mimikatz 대상)']},
    {'hive':'SAM', 'category':'계정 정보', 'severity':'medium',
     'path':'SAM\\Domains\\Account\\Users\\<RID>',
     'desc':'각 사용자별 폴더. RID 500=Admin, 501=Guest, 503=DefaultAccount, 504=WDAGUtility, 1000+=일반 사용자',
     'check':['1000번 이상 RID 모두 분석','관리자 그룹 멤버십']},
    {'hive':'SAM', 'category':'그룹', 'severity':'medium',
     'path':'SAM\\Domains\\Builtin\\Aliases\\Members\\',
     'desc':'그룹별 멤버 SID. Administrators(00000220), Backup Operators 등',
     'check':['Administrators 멤버 SID','권한 상승 흔적']},

    # ───── SYSTEM 하이브 ─────
    {'hive':'SYSTEM', 'category':'시스템 정보', 'severity':'info',
     'path':'ControlSet001\\Control\\ComputerName\\ComputerName',
     'desc':'컴퓨터 이름 (호스트명)',
     'check':['호스트명 = ComputerName 값']},
    {'hive':'SYSTEM', 'category':'시스템 정보', 'severity':'medium',
     'path':'ControlSet001\\Control\\TimeZoneInformation',
     'desc':'타임존 정보. Bias는 UTC 오프셋(분). 한국=-540.',
     'check':['Bias·ActiveTimeBias','TimeZoneKeyName','시각 비교 기준']},
    {'hive':'SYSTEM', 'category':'시스템 정보', 'severity':'info',
     'path':'Setup\\PendingFileRenameOperations',
     'desc':'재부팅 시 파일 이름변경/삭제 예정. 멀웨어가 흔적 제거에 사용.',
     'check':['삭제 예정 파일 확인']},
    {'hive':'SYSTEM', 'category':'서비스', 'severity':'high',
     'path':'ControlSet001\\Services\\',
     'desc':'모든 Windows 서비스. ImagePath, Start, Type 확인.',
     'check':['Start=2(자동) + 의심 ImagePath','svchost.exe -k 형태가 아닌 임의 EXE','새로 추가된 서비스']},
    {'hive':'SYSTEM', 'category':'USB·저장장치', 'severity':'high',
     'path':'ControlSet001\\Enum\\USBSTOR\\',
     'desc':'USB 저장장치 (USB 메모리·외장하드) 연결 이력. 디스크 클래스 → 시리얼 번호.',
     'check':['하위키 = VID&PID&Rev → 시리얼','FriendlyName','Mfg, Class, ClassGUID','마지막 연결·제거 시각 (0066/0067 GUID Properties)']},
    {'hive':'SYSTEM', 'category':'USB·저장장치', 'severity':'high',
     'path':'ControlSet001\\Enum\\USB\\',
     'desc':'모든 USB 장치 (마우스·키보드·웹캠 포함)',
     'check':['하위키 = VID&PID → 시리얼','HID 장치도 모두 추적']},
    {'hive':'SYSTEM', 'category':'USB·저장장치', 'severity':'high',
     'path':'MountedDevices',
     'desc':'마운트된 모든 디스크. \\DosDevices\\C: 등의 값에 디스크 시그니처·USB 시리얼.',
     'check':['드라이브 레터 → 디스크 매핑','USB 마운트 흔적','VolumeGUID']},
    {'hive':'SYSTEM', 'category':'네트워크', 'severity':'medium',
     'path':'ControlSet001\\Services\\Tcpip\\Parameters\\Interfaces\\<NIC GUID>',
     'desc':'네트워크 인터페이스 IP·서브넷·게이트웨이·DHCP 정보',
     'check':['IPAddress·DhcpIPAddress','DhcpServer (DHCP 정보)','DhcpNameServer']},
    {'hive':'SYSTEM', 'category':'사용자 활동', 'severity':'medium',
     'path':'ControlSet001\\Control\\BAM\\State\\UserSettings\\<SID>',
     'desc':'Background Activity Moderator: 각 실행파일별 마지막 실행 시각 (Win10+)',
     'check':['실행파일 경로 = 키 이름','값(8B FILETIME) = 마지막 실행']},
    {'hive':'SYSTEM', 'category':'사용자 활동', 'severity':'info',
     'path':'ControlSet001\\Control\\DAM\\State\\UserSettings\\<SID>',
     'desc':'Desktop Activity Moderator: BAM과 유사',
     'check':['BAM과 함께 확인']},

    # ───── SOFTWARE 하이브 ─────
    {'hive':'SOFTWARE', 'category':'시스템 정보', 'severity':'info',
     'path':'Microsoft\\Windows NT\\CurrentVersion',
     'desc':'Windows 버전·설치일·소유자·제품키 정보',
     'check':['ProductName','InstallDate (Unix sec)','RegisteredOwner','RegisteredOrganization','BuildLab','CurrentBuild·DisplayVersion','ProductId']},
    {'hive':'SOFTWARE', 'category':'자동실행', 'severity':'high',
     'path':'Microsoft\\Windows\\CurrentVersion\\Run',
     'desc':'⚠️ 부팅 시 자동 실행 (모든 사용자). 멀웨어 지속성 1순위.',
     'check':['모든 값의 경로 확인','정상 EXE인지 디지털 서명 검증','임시폴더·AppData 안의 의심 EXE']},
    {'hive':'SOFTWARE', 'category':'자동실행', 'severity':'high',
     'path':'Microsoft\\Windows\\CurrentVersion\\RunOnce',
     'desc':'다음 부팅 시 1회만 실행. 멀웨어 인스톨러 흔적.',
     'check':['값이 있다면 의심 (실행 후 자동 삭제됨)']},
    {'hive':'SOFTWARE', 'category':'자동실행', 'severity':'medium',
     'path':'Microsoft\\Windows\\CurrentVersion\\RunServices',
     'desc':'서비스 형태 자동 실행',
     'check':['Run과 동일 분석']},
    {'hive':'SOFTWARE', 'category':'자동실행', 'severity':'high',
     'path':'Microsoft\\Windows NT\\CurrentVersion\\Winlogon',
     'desc':'⚠️ Winlogon 키. Userinit·Shell·System·VmApplet 변조 시 매우 위험.',
     'check':['Userinit 정상값: userinit.exe','Shell 정상값: explorer.exe','다른 값 추가시 악성 의심']},
    {'hive':'SOFTWARE', 'category':'프로그램', 'severity':'medium',
     'path':'Microsoft\\Windows\\CurrentVersion\\Uninstall',
     'desc':'설치된 프로그램 목록. 사용자가 직접 제거할 수 있는 프로그램.',
     'check':['하위키별 DisplayName·InstallDate·Publisher','InstallSource·UninstallString']},
    {'hive':'SOFTWARE', 'category':'프로그램', 'severity':'medium',
     'path':'WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall',
     'desc':'32비트 프로그램 설치 목록 (64비트 Windows에서)',
     'check':['위와 동일']},
    {'hive':'SOFTWARE', 'category':'사용자 프로필', 'severity':'high',
     'path':'Microsoft\\Windows NT\\CurrentVersion\\ProfileList',
     'desc':'시스템의 모든 사용자 프로필 SID → 홈 디렉터리 매핑',
     'check':['하위키 = SID','ProfileImagePath = C:\\Users\\<name>','ProfileLoadTimeHigh/Low (FILETIME)']},
    {'hive':'SOFTWARE', 'category':'네트워크', 'severity':'high',
     'path':'Microsoft\\Windows NT\\CurrentVersion\\NetworkList\\Profiles\\<GUID>',
     'desc':'연결했던 Wi-Fi/유선 네트워크 프로필',
     'check':['ProfileName = SSID','DateCreated, DateLastConnected (SYSTEMTIME 16B)','NameType (0x47=무선)']},
    {'hive':'SOFTWARE', 'category':'네트워크', 'severity':'high',
     'path':'Microsoft\\Windows NT\\CurrentVersion\\NetworkList\\Signatures\\Unmanaged',
     'desc':'네트워크 시그니처 (게이트웨이 MAC 기반)',
     'check':['DefaultGatewayMac (6B raw)','FirstNetwork','Description']},
    {'hive':'SOFTWARE', 'category':'기타', 'severity':'low',
     'path':'Microsoft\\Cryptography',
     'desc':'MachineGuid: 시스템 고유 식별자 (텔레메트리 추적용)',
     'check':['MachineGuid 값 (UTF-16 UUID)']},

    # ───── NTUSER.DAT (사용자별) ─────
    {'hive':'NTUSER.DAT', 'category':'자동실행', 'severity':'high',
     'path':'Software\\Microsoft\\Windows\\CurrentVersion\\Run',
     'desc':'사용자별 자동실행. HKLM\\Run과 함께 검사 필수.',
     'check':['SOFTWARE Run과 동일 분석']},
    {'hive':'NTUSER.DAT', 'category':'사용자 활동', 'severity':'high',
     'path':'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist\\{75048700-EF1F-11D9-9D70-0050568C5BB7}\\Count',
     'desc':'⭐ UserAssist: 사용자가 실행한 프로그램 횟수·시각 (ROT13 인코딩)',
     'check':['ROT13 디코드 후 EXE 경로','72B 바이너리: 실행 횟수·마지막 실행 시각','창 포커스 시간']},
    {'hive':'NTUSER.DAT', 'category':'사용자 활동', 'severity':'high',
     'path':'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU',
     'desc':'Win+R 실행 대화상자 입력 이력',
     'check':['a~ 값에 입력 명령','MRUList = 사용 순서']},
    {'hive':'NTUSER.DAT', 'category':'사용자 활동', 'severity':'high',
     'path':'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\TypedPaths',
     'desc':'⭐ 탐색기 주소창에 직접 입력한 경로 (수동으로 폴더 접근)',
     'check':['url1~urlN 값','민감 폴더 접근 흔적']},
    {'hive':'NTUSER.DAT', 'category':'사용자 활동', 'severity':'high',
     'path':'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RecentDocs',
     'desc':'⭐ 최근 열람 파일 (확장자별 분류). 파일 접근의 핵심 증거.',
     'check':['하위키 = .확장자','각 값 = ShellLink 형식 (LNK 유사)','MRUListEx = 사용 순서']},
    {'hive':'NTUSER.DAT', 'category':'사용자 활동', 'severity':'medium',
     'path':'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\WordWheelQuery',
     'desc':'⭐ Windows 검색창 입력 키워드',
     'check':['0,1,2 등 숫자 값 = 검색어 (UTF-16)','MRUListEx = 순서']},
    {'hive':'NTUSER.DAT', 'category':'사용자 활동', 'severity':'medium',
     'path':'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ComDlg32\\OpenSavePidlMRU',
     'desc':'⭐ 파일 열기/저장 대화상자 이력 (각 확장자별)',
     'check':['확장자별 하위키','PIDL 시리얼화 형식 (ShellItem 리스트)']},
    {'hive':'NTUSER.DAT', 'category':'사용자 활동', 'severity':'medium',
     'path':'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ComDlg32\\LastVisitedPidlMRU',
     'desc':'마지막 방문 폴더 + 어떤 프로그램이 접근했는지',
     'check':['실행파일명 + PIDL 경로']},
    {'hive':'NTUSER.DAT', 'category':'웹 브라우저', 'severity':'medium',
     'path':'Software\\Microsoft\\Internet Explorer\\TypedURLs',
     'desc':'IE/Edge 주소창에 직접 입력한 URL',
     'check':['url1 = 가장 최근','TypedURLsTime 키와 함께 시각 추적']},
    {'hive':'NTUSER.DAT', 'category':'기타', 'severity':'info',
     'path':'Volatile Environment',
     'desc':'사용자별 환경변수 (USERNAME·USERPROFILE·APPDATA 등)',
     'check':['USERNAME = 로그인한 사용자명']},
    {'hive':'NTUSER.DAT', 'category':'기타', 'severity':'info',
     'path':'Software\\Microsoft\\Windows\\Shell\\BagMRU',
     'desc':'⭐ ShellBag: 탐색기로 접근한 모든 폴더 (USB 폴더 포함)',
     'check':['하위키 깊이 = 폴더 계층','각 값 = 폴더 ShellItem','BagMRU와 Bags 함께 분석']},

    # ───── UsrClass.dat ─────
    {'hive':'UsrClass.dat', 'category':'사용자 활동', 'severity':'high',
     'path':'Local Settings\\Software\\Microsoft\\Windows\\Shell\\BagMRU',
     'desc':'⭐ 본격 ShellBag (NTUSER보다 더 상세). USB·네트워크 폴더 접근.',
     'check':['하위키 계층 = 폴더 트리','각 값 = ShellItem (생성/접근/수정 DOS 시각)','BEEF0004 확장 블록 (MFT 엔트리)']},
    {'hive':'UsrClass.dat', 'category':'사용자 활동', 'severity':'medium',
     'path':'Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Repository\\Packages',
     'desc':'UWP 앱 설치 정보 (Windows 10+)',
     'check':['하위키 = 패키지 식별자','설치 시각·서명자']},

    # ───── Amcache.hve ─────
    {'hive':'Amcache.hve', 'category':'실행 이력', 'severity':'high',
     'path':'Root\\InventoryApplicationFile',
     'desc':'⭐⭐⭐ 시스템에 한 번이라도 실행된 모든 PE의 영구 기록 (Win10+). 파일이 삭제되도 흔적 남음.',
     'check':['LowerCaseLongPath','FileId = 0000+SHA1 (앞 31.4MB)','LinkDate (PE 컴파일 시각)','Size·Publisher·Version']},
    {'hive':'Amcache.hve', 'category':'실행 이력', 'severity':'medium',
     'path':'Root\\InventoryApplication',
     'desc':'설치된 응용프로그램 인벤토리',
     'check':['Name·Publisher·InstallDate']},
    {'hive':'Amcache.hve', 'category':'실행 이력', 'severity':'medium',
     'path':'Root\\InventoryDriverBinary',
     'desc':'설치된 드라이버 인벤토리',
     'check':['루트킷 드라이버 흔적']},
]


# ════════════════════════════════════════════════════════════════
# 2. 파일시스템 핵심 경로
# ════════════════════════════════════════════════════════════════
_FILESYSTEM_PATHS = [
    {'os':'Windows', 'category':'레지스트리 하이브',
     'path':'C:\\Windows\\System32\\config\\SAM',
     'desc':'로컬 계정 정보·해시 (관리자/SYSTEM 권한 필요)'},
    {'os':'Windows', 'category':'레지스트리 하이브',
     'path':'C:\\Windows\\System32\\config\\SECURITY',
     'desc':'보안 정책·LSA 시크릿'},
    {'os':'Windows', 'category':'레지스트리 하이브',
     'path':'C:\\Windows\\System32\\config\\SOFTWARE',
     'desc':'시스템 설치 프로그램·네트워크·자동실행'},
    {'os':'Windows', 'category':'레지스트리 하이브',
     'path':'C:\\Windows\\System32\\config\\SYSTEM',
     'desc':'서비스·드라이버·USB·MountedDevices'},
    {'os':'Windows', 'category':'레지스트리 하이브',
     'path':'C:\\Users\\<USER>\\NTUSER.DAT',
     'desc':'사용자별 자동실행·UserAssist·RecentDocs·ShellBag'},
    {'os':'Windows', 'category':'레지스트리 하이브',
     'path':'C:\\Users\\<USER>\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat',
     'desc':'사용자별 ShellBag (상세)·UWP 앱'},
    {'os':'Windows', 'category':'레지스트리 하이브',
     'path':'C:\\Windows\\AppCompat\\Programs\\Amcache.hve',
     'desc':'⭐ 실행 파일 영구 기록 (Win10+)'},
    {'os':'Windows', 'category':'이벤트 로그',
     'path':'C:\\Windows\\System32\\winevt\\Logs\\Security.evtx',
     'desc':'⭐ 보안 로그: 로그온(4624/4625), 권한(4672), 계정 변경(4720/4738)'},
    {'os':'Windows', 'category':'이벤트 로그',
     'path':'C:\\Windows\\System32\\winevt\\Logs\\System.evtx',
     'desc':'시스템 로그: 서비스 설치(7045), 로그 삭제(1102/104)'},
    {'os':'Windows', 'category':'이벤트 로그',
     'path':'C:\\Windows\\System32\\winevt\\Logs\\Microsoft-Windows-PowerShell%4Operational.evtx',
     'desc':'PowerShell 스크립트 블록 로깅 (4103/4104)'},
    {'os':'Windows', 'category':'이벤트 로그',
     'path':'C:\\Windows\\System32\\winevt\\Logs\\Microsoft-Windows-Sysmon%4Operational.evtx',
     'desc':'⭐⭐ Sysmon (설치된 경우): 프로세스(1)·네트워크(3)·이미지로드(7)·인젝션(8)'},
    {'os':'Windows', 'category':'실행 추적',
     'path':'C:\\Windows\\Prefetch\\*.pf',
     'desc':'⭐⭐ Prefetch: EXE별 실행 횟수·최근 8회 시각·참조 파일'},
    {'os':'Windows', 'category':'바로가기',
     'path':'C:\\Users\\<USER>\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\*.lnk',
     'desc':'⭐ 최근 파일 LNK: 대상 경로·MAC 주소·DroidBirth GUID'},
    {'os':'Windows', 'category':'JumpList',
     'path':'C:\\Users\\<USER>\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\AutomaticDestinations\\*.automaticDestinations-ms',
     'desc':'⭐ JumpList: 앱별 최근 파일·접근 횟수·시각·DroidBirth MAC'},
    {'os':'Windows', 'category':'USB 추적',
     'path':'C:\\Windows\\INF\\setupapi.dev.log',
     'desc':'⭐ USB 장치 최초 연결 시각 + 드라이버 설치'},
    {'os':'Windows', 'category':'휴지통',
     'path':'C:\\$Recycle.Bin\\<SID>\\$I*',
     'desc':'⭐ 휴지통 메타: 원본 경로·삭제 시각·크기'},
    {'os':'Windows', 'category':'썸네일',
     'path':'C:\\Users\\<USER>\\AppData\\Local\\Microsoft\\Windows\\Explorer\\thumbcache_*.db',
     'desc':'⭐ 썸네일 캐시: 삭제된 이미지 흔적 (CMMM)'},
    {'os':'Windows', 'category':'브라우저',
     'path':'C:\\Users\\<USER>\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\History',
     'desc':'Edge 방문 이력 SQLite (Chrome epoch)'},
    {'os':'Windows', 'category':'브라우저',
     'path':'C:\\Users\\<USER>\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\History',
     'desc':'Chrome 방문 이력·다운로드·검색'},
    {'os':'Windows', 'category':'브라우저',
     'path':'C:\\Users\\<USER>\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\*\\places.sqlite',
     'desc':'Firefox 방문 이력·북마크 (Mozilla epoch)'},
    {'os':'Windows', 'category':'SRUM (자원 사용)',
     'path':'C:\\Windows\\System32\\sru\\SRUDB.dat',
     'desc':'⭐ 앱별 네트워크 사용량·프로세스 시간 (ESE DB)'},
    {'os':'Windows', 'category':'MFT',
     'path':'C:\\$MFT',
     'desc':'⭐⭐ NTFS Master File Table: 모든 파일 메타데이터 (MAC 타임)'},
    {'os':'Windows', 'category':'MFT',
     'path':'C:\\$LogFile',
     'desc':'NTFS 트랜잭션 저널'},
    {'os':'Windows', 'category':'MFT',
     'path':'C:\\$Extend\\$UsnJrnl:$J',
     'desc':'⭐ USN 변경 저널: 파일 생성/삭제/이름변경 기록'},
    {'os':'Windows', 'category':'스왑·하이버네이션',
     'path':'C:\\pagefile.sys',
     'desc':'페이지 파일 — 메모리 일부가 디스크에 남음 (문자열 카빙 대상)'},
    {'os':'Windows', 'category':'스왑·하이버네이션',
     'path':'C:\\hiberfil.sys',
     'desc':'⭐ 최대 절전 모드 메모리 덤프 (메모리 분석 가능)'},
    {'os':'Linux', 'category':'사용자',
     'path':'/etc/passwd', 'desc':'사용자 목록 (해시는 /etc/shadow)'},
    {'os':'Linux', 'category':'사용자',
     'path':'/etc/shadow', 'desc':'비밀번호 해시 (root 권한 필요)'},
    {'os':'Linux', 'category':'사용자',
     'path':'/etc/group', 'desc':'그룹 목록 + 멤버'},
    {'os':'Linux', 'category':'사용자 활동',
     'path':'/home/<USER>/.bash_history', 'desc':'⭐ bash 명령 이력'},
    {'os':'Linux', 'category':'사용자 활동',
     'path':'/var/log/auth.log', 'desc':'⭐ 인증 로그: SSH·sudo·세션'},
    {'os':'Linux', 'category':'사용자 활동',
     'path':'/var/log/wtmp', 'desc':'성공 로그인 이력 (last 명령)'},
    {'os':'Linux', 'category':'사용자 활동',
     'path':'/var/log/btmp', 'desc':'실패 로그인 시도 (lastb)'},
    {'os':'Linux', 'category':'사용자 활동',
     'path':'/var/log/syslog', 'desc':'시스템 로그 (Debian/Ubuntu)'},
    {'os':'Linux', 'category':'영구성',
     'path':'/etc/crontab, /etc/cron.*/*', 'desc':'⭐ 시스템 cron 작업'},
    {'os':'Linux', 'category':'영구성',
     'path':'/home/<USER>/.bashrc, .profile', 'desc':'사용자 셸 시작 스크립트'},
    {'os':'Linux', 'category':'영구성',
     'path':'/etc/systemd/system/, /lib/systemd/system/', 'desc':'⭐ systemd 서비스'},
    {'os':'Linux', 'category':'영구성',
     'path':'/etc/rc.local', 'desc':'부팅 시 실행 스크립트 (오래된 시스템)'},
    {'os':'Linux', 'category':'네트워크',
     'path':'/etc/network/interfaces, /etc/netplan/', 'desc':'네트워크 설정'},
    {'os':'Linux', 'category':'네트워크',
     'path':'/var/log/journal/<UUID>/', 'desc':'⭐ systemd-journald 바이너리 로그'},
    {'os':'macOS', 'category':'사용자 활동',
     'path':'~/Library/Application Support/Knowledge/knowledgeC.db',
     'desc':'⭐ 앱 사용 이력·잠금/해제·Safari 히스토리'},
    {'os':'macOS', 'category':'사용자 활동',
     'path':'~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2',
     'desc':'⭐ Gatekeeper 격리 이력 (다운로드 URL·시각)'},
    {'os':'macOS', 'category':'사용자 활동',
     'path':'/Library/Application Support/com.apple.TCC/TCC.db',
     'desc':'⭐ 권한 부여 이력 (Camera·Mic·Contacts 등)'},
    {'os':'macOS', 'category':'영구성',
     'path':'~/Library/LaunchAgents/, /Library/LaunchAgents/, /Library/LaunchDaemons/',
     'desc':'⭐ 자동 시작 plist (.plist)'},
    {'os':'macOS', 'category':'영구성',
     'path':'~/Library/Preferences/com.apple.loginitems.plist',
     'desc':'로그인 항목 (UI 등록 자동시작)'},
    {'os':'macOS', 'category':'파일시스템',
     'path':'/.fseventsd/*.gz',
     'desc':'⭐ FSEvents: 파일시스템 모든 변경 이력 (gzip)'},
    {'os':'iOS', 'category':'백업',
     'path':'~/Library/Application Support/MobileSync/Backup/<UDID>/Manifest.db',
     'desc':'⭐ iTunes 백업 메타데이터 SQLite'},
    {'os':'iOS', 'category':'메시지',
     'path':'<백업>/3d/3d0d7e5fb2ce288813306e4d4636395e047a3d28',
     'desc':'⭐ sms.db (iMessage·SMS)'},
    {'os':'iOS', 'category':'사진',
     'path':'<백업>/12/12b144c0bd44f2b3dffd9186d3f9c05b917cee25',
     'desc':'Photos.sqlite (사진 메타)'},
    {'os':'Android', 'category':'연락처',
     'path':'/data/data/com.android.providers.contacts/databases/contacts2.db',
     'desc':'⭐ 연락처 + 통화기록 통합 DB'},
    {'os':'Android', 'category':'메시지',
     'path':'/data/data/com.android.providers.telephony/databases/mmssms.db',
     'desc':'⭐ SMS·MMS'},
    {'os':'Android', 'category':'Wi-Fi',
     'path':'/data/misc/wifi/wpa_supplicant.conf 또는 WifiConfigStore.xml',
     'desc':'⭐ Wi-Fi SSID + 비밀번호 (root 권한 필요)'},
]


# ════════════════════════════════════════════════════════════════
# 3. 초보자 시나리오 (단계별 워크플로)
# ════════════════════════════════════════════════════════════════
_BEGINNER_SCENARIOS = [
    {
        'id': 'start',
        'icon': 'bi-stars',
        'title': '🌱 처음이에요 — 어디서 시작?',
        'difficulty': '입문',
        'time': '5분',
        'desc': '포렌식이 처음이라면 이 도구부터 시작하세요.',
        'steps': [
            {'tool': '/tools/auto', 'name': '🪄 자동 분류 라우터',
             'why': '의심 파일을 업로드하면 자동으로 가장 적합한 도구를 추천합니다.',
             'tip': '뭘 해야 할지 모를 때 가장 먼저 쓰는 도구'},
            {'tool': '/tools/autoanalyze', 'name': '🤖 자동 분석',
             'why': '시그니처·엔트로피·IOC를 한 번에 검사합니다.',
             'tip': '결과를 보고 추천 도구로 깊이 분석 진행'},
            {'tool': '/tools/help', 'name': '❓ 전체 도움말',
             'why': '156개 도구의 사용법을 한눈에 검색.',
             'tip': '도구 이름·기능 키워드로 찾기'},
        ],
    },
    {
        'id': 'malware',
        'icon': 'bi-bug-fill',
        'title': '🦠 의심 파일을 받았어요',
        'difficulty': '초급',
        'time': '15분',
        'desc': '이메일로 받은 첨부파일·다운로드한 EXE 분석.',
        'steps': [
            {'tool': '/tools/hash', 'name': '1. 해시 계산',
             'why': '파일 SHA-256 계산 → VirusTotal 검색 가능. 무결성 검증 첫 단계.',
             'tip': '동료에게 해시만 공유해 안전하게 협업'},
            {'tool': '/tools/magic', 'name': '2. 매직바이트 확인',
             'why': '확장자가 .pdf인데 실제로는 .exe일 수도. 확장자-시그니처 불일치 탐지.',
             'tip': '확장자만 믿으면 안 됨'},
            {'tool': '/tools/entropy', 'name': '3. 엔트로피 측정',
             'why': '엔트로피 >7.5 = 암호화/패킹된 악성 가능성 높음.',
             'tip': '정상 EXE는 5.0~6.8 사이'},
            {'tool': '/tools/pe', 'name': '4. PE 헤더 분석',
             'why': '의심 API(VirtualAlloc·CreateRemoteThread·URLDownloadToFile) 자동 탐지.',
             'tip': '컴파일 시각이 너무 최근(어제·오늘)이면 의심'},
            {'tool': '/tools/strings', 'name': '5. 문자열 추출',
             'why': 'EXE 내부에 박힌 URL·IP·명령·악성 함수명.',
             'tip': '최소 길이 6, UTF-16 인코딩 포함'},
            {'tool': '/tools/ioc', 'name': '6. IOC 추출',
             'why': '발견된 URL·IP·해시·CVE를 자동 정리.',
             'tip': '발견된 도메인은 /tools/whois로 추적'},
            {'tool': '/tools/threat-intel', 'name': '7. 위협 인텔 조회',
             'why': 'VirusTotal·AbuseIPDB로 평판 확인 (API 키 입력).',
             'tip': '무료 VT 키는 virustotal.com에서 발급'},
            {'tool': '/tools/yara', 'name': '8. YARA 규칙 매칭',
             'why': '알려진 멀웨어 패밀리 자동 분류.',
             'tip': 'github.com/Yara-Rules에 공개 규칙'},
        ],
    },
    {
        'id': 'usb',
        'icon': 'bi-usb-symbol',
        'title': '💾 USB 의심 행위 추적',
        'difficulty': '중급',
        'time': '30분',
        'desc': '직원이 USB로 데이터를 빼냈는지 확인.',
        'steps': [
            {'tool': '/tools/registry', 'name': '1. SYSTEM 하이브 열기',
             'why': 'C:\\Windows\\System32\\config\\SYSTEM 업로드.',
             'tip': '아래 핵심 경로 가이드 참고'},
            {'path':'ControlSet001\\Enum\\USBSTOR\\', 'name': '2. USBSTOR 키 분석',
             'why': '연결됐던 모든 USB 저장장치 (디스크·외장하드).',
             'tip': 'VID&PID&Rev → 시리얼 → 마지막 연결 시각'},
            {'path':'MountedDevices', 'name': '3. MountedDevices',
             'why': 'USB가 어떤 드라이브 레터로 마운트됐는지.',
             'tip': '\\DosDevices\\E: 값에 USB 시리얼'},
            {'tool': '/tools/registry', 'name': '4. NTUSER.DAT 열기',
             'why': '의심 사용자의 NTUSER.DAT 업로드.'},
            {'path':'Software\\Microsoft\\Windows\\Shell\\BagMRU', 'name': '5. ShellBag',
             'why': '⭐ USB 안의 어떤 폴더를 탐색했는지 모두 기록.',
             'tip': 'UsrClass.dat의 ShellBag이 더 상세'},
            {'tool': '/tools/registry', 'name': '6. UsrClass.dat ShellBag',
             'why': 'C:\\Users\\<X>\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat'},
            {'tool': 'setupapi-log', 'name': '7. setupapi.dev.log',
             'why': '⭐ USB 최초 연결 시각·드라이버 설치 정확한 타임.',
             'tip': 'C:\\Windows\\INF\\setupapi.dev.log → /tools/log'},
        ],
    },
    {
        'id': 'logon',
        'icon': 'bi-person-fill-check',
        'title': '👤 사용자 계정·로그온 조사',
        'difficulty': '중급',
        'time': '20분',
        'desc': '누가 언제 로그온했는지·계정 변조 확인.',
        'steps': [
            {'tool': '/tools/registry', 'name': '1. SAM 하이브',
             'why': '로컬 계정 목록.'},
            {'path':'SAM\\Domains\\Account\\Users\\Names\\', 'name': '2. 계정 목록',
             'why': '하위키가 계정명. 모르는 계정 = 의심.',
             'tip': '500=Admin·501=Guest 외 1000+ 검사'},
            {'path':'SAM\\Domains\\Account\\Users\\<RID>\\F', 'name': '3. F 바이너리',
             'why': '⭐ 마지막 로그온·암호 변경·로그온 횟수.',
             'tip': '평소 안 쓰는 계정이 최근 로그온하면 의심'},
            {'tool': '/tools/evtx', 'name': '4. Security.evtx',
             'why': '⭐⭐ 보안 이벤트 로그.'},
            {'event':'4624', 'name': '5. EventID 4624',
             'why': '로그온 성공. LogonType: 2=대화형·10=RDP·3=네트워크·5=서비스.',
             'tip': 'LogonType 10 (RDP) = 원격 접속'},
            {'event':'4625', 'name': '6. EventID 4625',
             'why': '⭐ 로그온 실패. 무차별 공격 흔적.'},
            {'event':'4720', 'name': '7. EventID 4720',
             'why': '⭐ 사용자 계정 생성. 백도어 계정 의심.'},
            {'event':'4672', 'name': '8. EventID 4672',
             'why': '특권 할당. 관리자 권한 행사 시점.'},
        ],
    },
    {
        'id': 'execution',
        'icon': 'bi-play-circle-fill',
        'title': '▶️ 어떤 프로그램을 실행했는지',
        'difficulty': '초급',
        'time': '15분',
        'desc': '사용자가 무엇을 실행했는지 모든 추적.',
        'steps': [
            {'tool': '/tools/prefetch', 'name': '1. Prefetch 분석',
             'why': '⭐⭐ EXE별 실행 횟수·마지막 8회 시각.',
             'tip': 'C:\\Windows\\Prefetch\\*.pf 업로드'},
            {'tool': '/tools/registry', 'name': '2. NTUSER.DAT — UserAssist',
             'why': '⭐ 사용자가 GUI로 실행한 모든 프로그램 (ROT13).',
             'tip': 'Explorer\\UserAssist\\{GUID}\\Count'},
            {'tool': '/tools/amcache', 'name': '3. AmCache.hve',
             'why': '⭐⭐⭐ 실행됐던 모든 PE의 영구 기록 (Win10+, 삭제돼도 남음).',
             'tip': 'C:\\Windows\\AppCompat\\Programs\\Amcache.hve'},
            {'path':'ControlSet001\\Control\\BAM\\State\\UserSettings\\', 'name': '4. BAM (SYSTEM)',
             'why': '사용자별 각 EXE 마지막 실행 시각 (Win10+).'},
            {'tool': '/tools/evtx', 'name': '5. Security 4688',
             'why': '프로세스 생성 로그 (감사 정책 설정 필요).'},
            {'tool': '/tools/evtx', 'name': '6. Sysmon Event 1',
             'why': '⭐⭐ Sysmon이 설치됐다면 모든 프로세스 + 명령행.',
             'tip': 'Microsoft-Windows-Sysmon%4Operational.evtx'},
        ],
    },
    {
        'id': 'browser',
        'icon': 'bi-globe',
        'title': '🌐 부적절한 웹 접근 조사',
        'difficulty': '초급',
        'time': '20분',
        'desc': '방문한 사이트·다운로드·검색 이력.',
        'steps': [
            {'tool': '/tools/sqlite', 'name': '1. Chrome History',
             'why': 'C:\\Users\\<X>\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\History',
             'tip': 'urls 테이블 = 방문 이력, downloads = 다운로드'},
            {'sql':"SELECT url,title,last_visit_time FROM urls ORDER BY last_visit_time DESC LIMIT 100",
             'name': '2. 최근 방문 쿼리',
             'why': 'last_visit_time은 Chrome epoch (μs since 1601).'},
            {'tool': '/tools/time', 'name': '3. 시각 변환',
             'why': 'Chrome epoch 값을 입력하면 사람이 읽는 시각으로.'},
            {'tool': '/tools/sqlite', 'name': '4. Firefox places.sqlite',
             'why': '~\\Mozilla\\Firefox\\Profiles\\*.default\\places.sqlite',
             'tip': 'moz_places, moz_historyvisits 테이블'},
            {'tool': '/tools/registry', 'name': '5. NTUSER TypedURLs',
             'why': 'IE/Edge 주소창에 직접 입력한 URL.'},
            {'tool': '/tools/har', 'name': '6. HAR 분석 (있을 때)',
             'why': '브라우저 개발자도구 → Network → Save as HAR.'},
        ],
    },
    {
        'id': 'phishing',
        'icon': 'bi-envelope-exclamation-fill',
        'title': '✉️ 피싱 이메일 분석',
        'difficulty': '초급',
        'time': '15분',
        'desc': '의심 이메일의 발신자·경유 경로·첨부파일 검증.',
        'steps': [
            {'tool': '/tools/email', 'name': '1. .eml 파일 분석',
             'why': '헤더·발신경로·첨부·스푸핑 자동 탐지.'},
            {'tool': '/tools/emaildeep', 'name': '2. 헤더 심층',
             'why': '⭐ From vs Return-Path 도메인 불일치 = 스푸핑.',
             'tip': 'Authentication-Results 헤더 확인'},
            {'tool': '/tools/email-auth', 'name': '3. SPF/DKIM/DMARC',
             'why': '발신 도메인의 인증 정책 확인.',
             'tip': '도메인 입력으로 DNS TXT 조회'},
            {'tool': '/tools/urlsafe', 'name': '4. 본문 URL 검사',
             'why': 'Punycode 피싱·단축 URL·@호스트 의심 패턴.'},
            {'tool': '/tools/pdfscan', 'name': '5. PDF 첨부',
             'why': '/JavaScript /OpenAction /Launch 의심.'},
            {'tool': '/tools/oledump', 'name': '6. Office 첨부',
             'why': '.doc·.xlsm VBA 매크로 + 의심 키워드.'},
            {'tool': '/tools/ioc', 'name': '7. IOC 추출',
             'why': '본문에서 모든 URL·IP·해시 추출.'},
        ],
    },
    {
        'id': 'image',
        'icon': 'bi-camera-fill',
        'title': '📷 사진 분석 (위치·시각·카메라)',
        'difficulty': '초급',
        'time': '10분',
        'desc': '사진이 언제·어디서·어떤 카메라로 찍혔는지.',
        'steps': [
            {'tool': '/tools/metadata', 'name': '1. EXIF 메타데이터',
             'why': '카메라·렌즈·셔터·ISO·촬영 시각.'},
            {'tool': '/tools/gps', 'name': '2. GPS 좌표 + 지도',
             'why': '⭐ 정확한 촬영 위치 + OpenStreetMap 핀.',
             'tip': 'SNS 업로드 사진은 EXIF 제거되는 경우 많음'},
            {'tool': '/tools/stego', 'name': '3. 스테가노그래피 검사',
             'why': '이미지에 숨겨진 데이터 (LSB·EOF).'},
            {'tool': '/tools/phash', 'name': '4. 유사 이미지 검색',
             'why': '여러 사진의 perceptual hash 비교.',
             'tip': '동일 원본의 편집본 식별'},
            {'tool': '/tools/face', 'name': '5. 얼굴 감지',
             'why': '사진 속 얼굴 자동 감지·위치.'},
            {'tool': '/tools/heif', 'name': '6. iOS HEIC',
             'why': 'iPhone 사진은 .heic 포맷.'},
        ],
    },
    {
        'id': 'powershell',
        'icon': 'bi-terminal',
        'title': '💻 PowerShell 악성 스크립트 분석',
        'difficulty': '중급',
        'time': '20분',
        'desc': '난독화된 PowerShell 코드 해독.',
        'steps': [
            {'tool': '/tools/psdeobf', 'name': '1. 자동 디오브푸',
             'why': 'Base64·-EncodedCommand·char[]·문자열 연결 자동 펴기.'},
            {'tool': '/tools/decode', 'name': '2. 수동 디코드',
             'why': '인코딩된 부분 따로 디코드.'},
            {'tool': '/tools/ioc', 'name': '3. IOC 추출',
             'why': '디오브푸 결과에서 URL·IP·파일경로 추출.'},
            {'tool': '/tools/attack', 'name': '4. ATT&CK 매핑',
             'why': '발견 행위를 MITRE 기법으로 자동 매핑.',
             'tip': 'powershell→T1059, mimikatz→T1003'},
            {'tool': '/tools/evtx', 'name': '5. PowerShell EVTX',
             'why': '⭐ Microsoft-Windows-PowerShell%4Operational.evtx, EventID 4103·4104.'},
        ],
    },
    {
        'id': 'memory',
        'icon': 'bi-memory',
        'title': '🧠 메모리 덤프 분석',
        'difficulty': '상급',
        'time': '60분+',
        'desc': '서버 침해 후 RAM 덤프에서 실행 중이던 프로세스 추적.',
        'steps': [
            {'tool': '/tools/scripts', 'name': '0. RAM 덤프 수집',
             'why': 'forensiclab_ram_dumper.py로 .raw 생성 (관리자 권한).'},
            {'tool': '/tools/memscan', 'name': '1. 빠른 IOC 스캔',
             'why': '문자열 기반 URL·프로세스·자격증명 단서.'},
            {'tool': '/tools/vol-full', 'name': '2. Volatility 풀 분석',
             'why': '⭐⭐⭐ pslist·malfind·netscan·dlllist 등 23개 플러그인.',
             'tip': '시간 오래 걸림 (백그라운드 작업)'},
            {'tool': 'pslist', 'name': '3. windows.pslist.PsList',
             'why': '실행 중인 프로세스 목록.'},
            {'tool': 'malfind', 'name': '4. windows.malfind.Malfind',
             'why': '⭐ 코드 인젝션 의심 메모리 영역.'},
            {'tool': 'netscan', 'name': '5. windows.netscan.NetScan',
             'why': '활성 네트워크 연결.'},
            {'tool': '/tools/strings', 'name': '6. 문자열 카빙',
             'why': '메모리 덤프에서 평문 자격증명·URL.'},
        ],
    },
    {
        'id': 'mobile',
        'icon': 'bi-phone-fill',
        'title': '📱 모바일 (iOS·Android) 포렌식',
        'difficulty': '중급',
        'time': '30분+',
        'desc': '스마트폰 백업·추출 파일 분석.',
        'steps': [
            {'tool': '/tools/ios-backup', 'name': '[iOS] 1. Manifest.db',
             'why': 'iTunes 백업의 모든 파일 매핑.',
             'tip': '~/Library/Application Support/MobileSync/Backup/<UDID>/Manifest.db'},
            {'tool': '/tools/ios-sms', 'name': '[iOS] 2. sms.db',
             'why': 'iMessage·SMS 메시지.'},
            {'tool': '/tools/ios-photos', 'name': '[iOS] 3. Photos.sqlite',
             'why': '사진 메타·앨범·삭제 이력.'},
            {'tool': '/tools/ileapp', 'name': '[iOS] 4. iLEAPP 풀세트 (PRO)',
             'why': '⭐⭐⭐ 300+ 아티팩트 자동 (Cellebrite UFED 대체).'},
            {'tool': '/tools/android-sms', 'name': '[Android] 1. mmssms.db',
             'why': 'SMS·MMS.'},
            {'tool': '/tools/android-calllog', 'name': '[Android] 2. calllog.db',
             'why': '통화 기록.'},
            {'tool': '/tools/android-wifi', 'name': '[Android] 3. Wi-Fi',
             'why': 'wpa_supplicant.conf → SSID·비밀번호.'},
            {'tool': '/tools/aleapp', 'name': '[Android] 4. ALEAPP 풀세트 (PRO)',
             'why': '⭐⭐⭐ 200+ 아티팩트 자동.'},
            {'tool': '/tools/apk', 'name': '[Android] 5. APK 분석',
             'why': '의심 APK의 권한·서명.'},
        ],
    },
    {
        'id': 'case',
        'icon': 'bi-folder-fill',
        'title': '📂 사건 만들기 → 통합 보고서',
        'difficulty': '중급',
        'time': '30분+',
        'desc': '여러 증거를 사건으로 묶어서 PDF 보고서 자동 생성.',
        'steps': [
            {'tool': '/login', 'name': '0. 로그인',
             'why': '사건 관리는 로그인 필요. 회원가입 후 시작.'},
            {'tool': '/tools/case', 'name': '1. 새 사건 생성',
             'why': '사건번호·이름·우선순위 입력.'},
            {'tool': '/tools/case', 'name': '2. 증거 업로드',
             'why': '각 증거 파일에 자동 SHA-256 + Chain of Custody 등록.'},
            {'tool': '/tools/case', 'name': '3. 발견사항 작성',
             'why': '심각도·MITRE ATT&CK·설명 기록.'},
            {'tool': '/tools/case', 'name': '4. 멤버 추가 (협업)',
             'why': '⭐ 관리자/수정자/검토자 역할 부여.'},
            {'tool': '/tools/case/<id>/report', 'name': '5. PDF 보고서',
             'why': '⭐ 6섹션 자동 생성 (개요·증거·발견·메모·CoC).'},
            {'tool': '/tools/coc', 'name': '6. Chain of Custody 확인',
             'why': 'SHA-256 해시 사슬 무결성 검증.'},
            {'tool': '/tools/llm-report', 'name': '7. AI narrative (선택)',
             'why': 'Claude API로 전문가 수준 보고서 생성.',
             'tip': 'Anthropic API 키 필요'},
        ],
    },
]


# ════════════════════════════════════════════════════════════════
# 4. 용어집
# ════════════════════════════════════════════════════════════════
_GLOSSARY = [
    ('SAM','Security Account Manager. Windows 로컬 계정 정보·해시 저장.'),
    ('RID','Relative Identifier. 사용자/그룹 식별 번호. 500=Admin, 501=Guest, 1000+=일반.'),
    ('SID','Security Identifier. 사용자/그룹의 고유 식별자 (S-1-5-21-...-1000 형식).'),
    ('NT 해시','MD4(UTF-16 LE 패스워드). LM 해시 후속·NTLM 인증에 사용.'),
    ('FILETIME','Windows 시각 형식. 1601-01-01 UTC부터 100나노초 단위.'),
    ('UnixTime','1970-01-01 UTC부터 초 단위.'),
    ('Chrome epoch','Chrome SQLite의 시각. 1601-01-01부터 마이크로초 단위.'),
    ('UserAssist','사용자가 실행한 프로그램 기록. 키 이름이 ROT13 인코딩.'),
    ('Prefetch','Windows가 실행 가속을 위해 만든 파일. 실행 흔적 강력한 증거 (.pf).'),
    ('Amcache','Win10+ 실행파일 영구 인벤토리. 파일이 삭제돼도 흔적 남음.'),
    ('ShellBag','탐색기로 본 적이 있는 폴더의 표시 설정. 폴더 접근 흔적.'),
    ('JumpList','앱별 최근 접근 파일 (작업표시줄 우클릭 메뉴).'),
    ('MFT','Master File Table. NTFS 모든 파일의 메타데이터 (MAC 타임).'),
    ('USN Journal','NTFS 파일 변경 저널. 생성/삭제/이름변경 기록.'),
    ('LNK','Windows 바로가기 파일. 대상 경로·MAC 주소·볼륨 정보 포함.'),
    ('EVTX','Windows 이벤트 로그 XML 형식 (Vista+).'),
    ('SRUM','System Resource Usage Monitor. 앱별 자원 사용량 (ESE DB).'),
    ('PE','Portable Executable. Windows .exe/.dll 형식.'),
    ('IOC','Indicator of Compromise. 침해 증거 (해시·IP·도메인 등).'),
    ('CoC','Chain of Custody. 증거 보관 사슬·무결성 추적.'),
    ('ATT&CK','MITRE의 적대적 전술·기법 분류. T1059=명령행 실행, T1003=자격증명 덤프 등.'),
    ('YARA','악성코드 패턴 매칭 규칙 언어.'),
    ('Sigma','범용 로그 탐지 규칙 (YAML).'),
    ('Volatility','메모리 덤프 분석 표준 도구.'),
    ('Plaso','log2timeline + psort로 다중 소스 통합 슈퍼 타임라인.'),
    ('ALEAPP','Android Logs Events And Protobuf Parser. 200+ 아티팩트.'),
    ('iLEAPP','iOS 버전. 300+ 아티팩트.'),
    ('EXIF','Exchangeable Image File. 사진 메타데이터 (카메라·GPS·시각).'),
    ('DroidBirth','LNK 파일에 박힌 MAC 주소 (생성된 PC NIC).'),
    ('스테가노그래피','파일에 정보를 숨기는 기술 (LSB·EOF).'),
    ('Punycode','국제화 도메인 인코딩. 호모그래프 피싱에 사용.'),
    ('SPF/DKIM/DMARC','이메일 인증 표준 — 발신 도메인 신뢰성 확인.'),
    ('PCAP','패킷 캡처 파일.'),
    ('libyal','Joachim Metz의 포렌식 라이브러리 모음 (libewf·libfsntfs 등).'),
]


# ════════════════════════════════════════════════════════════════
# 라우트
# ════════════════════════════════════════════════════════════════
# ════════════════════════════════════════════════════════════════
# 도구별 핵심 경로·정보 매핑 (페이지 상단 자동 표시)
# ════════════════════════════════════════════════════════════════
_TOOL_RELATED_PATHS = {
    # === Windows 레지스트리 ===
    'registry': {
        'title': '레지스트리 핵심 경로',
        'icon': 'bi-diagram-2-fill',
        'sections': [
            {'name': '🔴 자동실행 (멀웨어 지속성 #1)', 'paths': [
                ('SOFTWARE', 'Microsoft\\Windows\\CurrentVersion\\Run', '⭐ 시스템 자동실행'),
                ('SOFTWARE', 'Microsoft\\Windows\\CurrentVersion\\RunOnce', '1회 실행 (인스톨러 흔적)'),
                ('SOFTWARE', 'Microsoft\\Windows NT\\CurrentVersion\\Winlogon', 'Userinit·Shell 변조 위험'),
                ('NTUSER.DAT', 'Software\\Microsoft\\Windows\\CurrentVersion\\Run', '사용자별 자동실행'),
            ]},
            {'name': '🟠 사용자 활동 추적', 'paths': [
                ('NTUSER.DAT', 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist', '⭐ GUI 실행 이력 (ROT13)'),
                ('NTUSER.DAT', 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RecentDocs', '최근 문서'),
                ('NTUSER.DAT', 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\TypedPaths', '탐색기 주소창 입력'),
                ('NTUSER.DAT', 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU', 'Win+R 실행 이력'),
                ('NTUSER.DAT', 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\WordWheelQuery', '검색창 키워드'),
                ('NTUSER.DAT', 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ComDlg32\\OpenSavePidlMRU', '열기/저장 대화상자'),
                ('UsrClass.dat', 'Local Settings\\Software\\Microsoft\\Windows\\Shell\\BagMRU', '⭐ ShellBag (폴더 접근)'),
            ]},
            {'name': '💾 USB·장치', 'paths': [
                ('SYSTEM', 'ControlSet001\\Enum\\USBSTOR', '⭐ USB 저장장치 이력'),
                ('SYSTEM', 'ControlSet001\\Enum\\USB', '모든 USB 장치'),
                ('SYSTEM', 'MountedDevices', '드라이브 레터 매핑'),
            ]},
            {'name': '👤 계정 (SAM)', 'paths': [
                ('SAM', 'Domains\\Account\\Users\\Names', '계정명 목록'),
                ('SAM', 'Domains\\Account\\Users\\<RID>\\F', '⭐ 마지막 로그온·암호변경 (8B FILETIME)'),
                ('SAM', 'Domains\\Account\\Users\\<RID>\\V', '⭐ 계정명·전체이름·LM/NT 해시'),
            ]},
            {'name': '🌐 네트워크', 'paths': [
                ('SOFTWARE', 'Microsoft\\Windows NT\\CurrentVersion\\NetworkList\\Profiles', '연결 Wi-Fi/유선'),
                ('SOFTWARE', 'Microsoft\\Windows NT\\CurrentVersion\\NetworkList\\Signatures\\Unmanaged', '게이트웨이 MAC'),
                ('SYSTEM', 'ControlSet001\\Services\\Tcpip\\Parameters\\Interfaces\\<GUID>', 'IP·DHCP 설정'),
            ]},
            {'name': '⚙ 서비스·실행 추적', 'paths': [
                ('SYSTEM', 'ControlSet001\\Services', '서비스 목록 (ImagePath 의심)'),
                ('SYSTEM', 'ControlSet001\\Control\\BAM\\State\\UserSettings\\<SID>', '⭐ 앱별 마지막 실행 (Win10+)'),
                ('Amcache.hve', 'Root\\InventoryApplicationFile', '⭐⭐⭐ 실행파일 영구 인벤토리'),
            ]},
        ],
    },

    'evtx': {
        'title': '핵심 이벤트 ID + 로그 위치',
        'icon': 'bi-journal-text',
        'files': [
            'C:\\Windows\\System32\\winevt\\Logs\\Security.evtx',
            'C:\\Windows\\System32\\winevt\\Logs\\System.evtx',
            'C:\\Windows\\System32\\winevt\\Logs\\Application.evtx',
            'C:\\Windows\\System32\\winevt\\Logs\\Microsoft-Windows-PowerShell%4Operational.evtx',
            'C:\\Windows\\System32\\winevt\\Logs\\Microsoft-Windows-Sysmon%4Operational.evtx',
        ],
        'event_ids': [
            ('Security', '4624', '⭐ 로그온 성공 (LogonType: 2=대화형, 3=네트워크, 10=RDP)'),
            ('Security', '4625', '⭐ 로그온 실패 (무차별 공격)'),
            ('Security', '4634', '로그오프'),
            ('Security', '4648', '명시적 자격증명 로그온'),
            ('Security', '4672', '특권 할당 (관리자 권한)'),
            ('Security', '4688', '⭐ 프로세스 생성 (감사 정책 필요)'),
            ('Security', '4720', '⭐ 사용자 계정 생성'),
            ('Security', '4738', '사용자 계정 변경'),
            ('Security', '4768', 'Kerberos TGT 발급'),
            ('Security', '4769', 'Kerberos 서비스 티켓'),
            ('Security', '4776', 'NTLM 인증'),
            ('System', '7045', '⭐ 서비스 설치 (멀웨어 지속성)'),
            ('System', '7036', '서비스 시작/중지'),
            ('System', '104', '⭐⭐ 로그 삭제 (수동)'),
            ('System', '1102', '⭐⭐ 보안 로그 삭제 (Security.evtx)'),
            ('System', '6005', '부팅'),
            ('System', '6006', '정상 종료'),
            ('System', '6008', '비정상 종료'),
            ('PowerShell', '4103', '파이프라인 실행'),
            ('PowerShell', '4104', '⭐ 스크립트 블록 (난독화 디오브푸 후)'),
            ('Sysmon', '1', '⭐⭐ ProcessCreate + 전체 명령행'),
            ('Sysmon', '3', '⭐ NetworkConnect'),
            ('Sysmon', '7', 'ImageLoad (DLL 인젝션)'),
            ('Sysmon', '8', '⭐ CreateRemoteThread (인젝션)'),
            ('Sysmon', '10', 'ProcessAccess (메모리 읽기)'),
            ('Sysmon', '11', 'FileCreate'),
            ('Sysmon', '13', 'RegistrySet'),
            ('Sysmon', '22', '⭐ DnsQuery'),
        ],
    },

    'prefetch': {
        'title': 'Prefetch 파일 위치 + 분석 포인트',
        'icon': 'bi-fast-forward-fill',
        'files': ['C:\\Windows\\Prefetch\\*.pf'],
        'notes': [
            '파일명 형식: <EXE명>-<8자 해시>.pf (예: NOTEPAD.EXE-D8414F97.pf)',
            '해시는 EXE 전체 경로의 hash (다른 경로의 같은 EXE → 다른 .pf)',
            '버전: XP=v17, Vista/7=v23, Win8.1=v26, Win10/11=v30/31',
            'Win10+는 MAM 압축 (MAM\\x84 시그니처) — libscca-python으로 해제',
            '최근 8개 실행 시각 + 실행 횟수 + 참조 DLL/파일 경로 확인',
            '⚠️ Win10에서 SSD에서는 Prefetch 비활성화될 수 있음',
        ],
    },

    'lnk': {
        'title': 'LNK 위치 + 핵심 필드',
        'icon': 'bi-link-45deg',
        'files': [
            'C:\\Users\\<USER>\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\*.lnk',
            'C:\\Users\\<USER>\\Desktop\\*.lnk',
            'C:\\Users\\<USER>\\AppData\\Roaming\\Microsoft\\Office\\Recent\\*.lnk',
            'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\*.lnk',
        ],
        'notes': [
            'TargetPath: 바로가기가 가리키는 실제 파일 경로',
            'TargetIDList: PIDL (ShellItem 리스트) — 원본 위치 추적',
            '⭐ DroidBirth MAC: LNK 생성 PC의 NIC MAC 주소 (12B 중 마지막 6B)',
            'VolumeLabel + DriveSerial: 원본 디스크 식별 (USB 추적!)',
            'NetworkPath: 네트워크 공유 경로',
            'MAC 타임스탬프 3개: 생성·수정·접근',
            'WorkingDirectory + Arguments: 실행 인수',
            'IconLocation: 아이콘 출처 (UNC 경로 가능 → 자격증명 도용)',
        ],
    },

    'jumplist': {
        'title': 'JumpList 위치 + 분석',
        'icon': 'bi-bookmark-fill',
        'files': [
            'C:\\Users\\<USER>\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\AutomaticDestinations\\*.automaticDestinations-ms',
            'C:\\Users\\<USER>\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\CustomDestinations\\*.customDestinations-ms',
        ],
        'notes': [
            '파일명 = AppID (FNV-1a hash of 앱 실행 경로)',
            '주요 AppID: 5f7b5f1e01b83767=메모장, 9b9cdc69c1c24e2b=파일 탐색기, 28c8b86deab549a1=Chrome',
            'OLECF 컨테이너 → DestList 스트림 (메타데이터) + 번호 스트림 (개별 LNK)',
            'DestList: EntryID·LastAccess·AccessCount·Hostname·Path·DroidBirth (MAC)',
            'AppID 목록: https://github.com/EricZimmerman/JLECmd/blob/master/JLECmd/AppIDs.csv',
        ],
    },

    'mft': {
        'title': '$MFT 분석 포인트',
        'icon': 'bi-list-columns-reverse',
        'files': ['C:\\$MFT', 'C:\\$LogFile', 'C:\\$Extend\\$UsnJrnl:$J'],
        'notes': [
            '$MFT 위치: NTFS 볼륨 시작부 (기본). 모든 파일의 메타데이터.',
            '레코드 크기 1024 bytes, "FILE" 매직바이트',
            '$STANDARD_INFORMATION (0x10): 4개 FILETIME (C/M/A/E)',
            '$FILE_NAME (0x30): 파일명 + 4개 FILETIME (백업본)',
            '⭐ Timestomp 탐지: $SI vs $FN 시각 불일치',
            '$DATA (0x80): 본문 (resident or non-resident)',
            '$INDEX_ROOT (0x90) / $INDEX_ALLOCATION (0xA0): 디렉터리 인덱스',
            '삭제 플래그: 헤더 offset 0x16의 bit 0 (InUse=0이면 삭제됨)',
        ],
        'related_paths': [
            ('파일시스템', '$Recycle.Bin\\<SID>\\$I*', '휴지통 메타 (원본 경로·삭제 시각)'),
            ('파일시스템', '$Recycle.Bin\\<SID>\\$R*', '휴지통 실제 데이터'),
        ],
    },

    'amcache': {
        'title': 'AmCache 분석 포인트',
        'icon': 'bi-app-indicator',
        'files': ['C:\\Windows\\AppCompat\\Programs\\Amcache.hve'],
        'notes': [
            '⭐⭐⭐ Win10+ 실행파일 영구 인벤토리 — 파일이 삭제돼도 흔적 남음',
            '주요 키: Root\\InventoryApplicationFile\\<filename>|<sha1_prefix>',
            'FileId 값 = "0000" + SHA1(파일 처음 31.4MB) — VirusTotal 검색 가능',
            'LowerCaseLongPath = 실행 당시 파일 전체 경로',
            'LinkDate = PE 컴파일 타임 (MM/DD/YYYY HH:MM:SS)',
            'Size = 파일 크기, BinaryType = pe32 / pe64',
            'Publisher = 디지털 서명 발행자',
            'Win7 이하: Root\\File\\<VolGUID>\\<MFTRef> 형식 (다른 구조)',
        ],
    },

    'oledump': {
        'title': 'Office 분석 + 의심 키워드',
        'icon': 'bi-file-earmark-word-fill',
        'notes': [
            'OLE2 (Office 97-2003): .doc·.xls·.ppt — D0 CF 11 E0 시그니처',
            'OOXML (Office 2007+): .docx·.xlsx·.pptm — ZIP (PK\\x03\\x04)',
            'VBA 매크로: vbaProject.bin (OOXML) 또는 Macros/VBA/Module (OLE2)',
            'XLM 4.0 매크로: macrosheets/ 폴더 (의심도 매우 높음)',
            '⭐ VBA Stomping: PerformanceCache(p-code) 있고 CompressedSourceCode 없음',
        ],
        'suspicious_keywords': [
            'AutoOpen', 'Document_Open', 'Workbook_Open', 'Auto_Exec',
            'Shell.Application', 'WScript.Shell', 'powershell', 'cmd.exe',
            'http://', 'https://', 'ActiveXObject', 'Scripting.FileSystemObject',
            'CreateObject', 'GetObject', 'Wscript.CreateObject',
            'URLDownloadToFile', 'Net.WebClient', 'Invoke-Expression',
            'CALL', 'EXEC', 'REGISTER', 'FOPEN', 'FWRITE',
        ],
    },

    'pdfscan': {
        'title': '의심 PDF 객체',
        'icon': 'bi-file-earmark-pdf-fill',
        'notes': [
            'PDF 시그니처: %PDF-1.x',
            'EOF: %%EOF (여러 개면 incremental update — 변조 추적)',
        ],
        'suspicious_keywords': [
            '/JavaScript', '/JS', '/OpenAction', '/AA (Additional Action)',
            '/Launch (Acrobat 7+에서 차단되지만 우회 시도)',
            '/EmbeddedFile (첨부 파일)', '/RichMedia (Flash)',
            '/SubmitForm', '/GoToR (외부 PDF)', '/GoToE (임베디드 PDF)',
            '/URI (외부 링크)', '/XFA (Adobe XML Form)',
            '/ImportData', '/AcroForm',
        ],
    },

    'pe': {
        'title': 'PE 분석 + 의심 API',
        'icon': 'bi-cpu-fill',
        'notes': [
            'PE 시그니처: MZ (offset 0) + PE\\x00\\x00 (offset = e_lfanew)',
            '머신 타입: 0x014c=x86, 0x8664=x64, 0xaa64=ARM64',
            '서브시스템: 2=GUI, 3=CUI(콘솔), 1=NATIVE(드라이버)',
            '⭐ 컴파일 시각: COFF header offset 8 (Unix timestamp)',
            '⭐ 섹션 엔트로피 >7.0 = 패킹/암호화',
            '의심 섹션명: .text + UPX0/UPX1 (UPX 패커), .vmp (VMProtect)',
        ],
        'suspicious_apis': [
            'VirtualAlloc / VirtualProtect (메모리 할당·실행 권한)',
            'WriteProcessMemory + CreateRemoteThread (인젝션)',
            'NtUnmapViewOfSection (Process Hollowing)',
            'LoadLibraryA + GetProcAddress (동적 API 해석)',
            'URLDownloadToFile / InternetOpen (다운로더)',
            'WinExec / ShellExecute / CreateProcess',
            'RegSetValueEx (지속성)',
            'CryptEncrypt (랜섬웨어)',
            'OpenProcess (다른 프로세스 접근)',
            'SetWindowsHookEx (키로깅)',
            'Wow64DisableWow64FsRedirection (32→64 우회)',
        ],
    },

    'fsevents': {
        'title': 'macOS FSEvents 위치',
        'icon': 'bi-eye-fill',
        'files': ['/.fseventsd/<8자hex>.gz'],
        'notes': [
            'gzip 압축 — 풀면 1SLD/2SLD/3SLD 시그니처',
            '레코드: Path (UTF-8 NUL) + EventID (8B) + Flags (4B) [+ FileID (8B) on 2SLD]',
            'Flags: 0x01=생성, 0x02=삭제, 0x04=inode 변경, 0x08=이름변경, 0x10=수정',
            '⭐ 시간 정보는 없음 — 이벤트 ID 순서만 추적',
            'fseventsd가 정기적으로 정리하므로 모든 이벤트가 남지는 않음',
        ],
    },

    'knowledgec': {
        'title': 'KnowledgeC.db 분석',
        'icon': 'bi-clock-fill',
        'files': [
            '~/Library/Application Support/Knowledge/knowledgeC.db',
            '/private/var/db/CoreDuet/Knowledge/knowledgeC.db',
        ],
        'notes': [
            '핵심 테이블: ZOBJECT (이벤트), ZSTRUCTUREDMETADATA, ZSOURCE',
            '시각: Cocoa epoch (2001-01-01 UTC 기준 초)',
            '주요 스트림 (ZSTREAMNAME):',
            '  /app/usage = 앱 사용 시간',
            '  /app/inFocus = 활성 앱',
            '  /app/install = 앱 설치',
            '  /safari/history = Safari 방문',
            '  /device/isLocked = 잠금 상태',
            '  /device/isBacklit = 화면 켜짐',
            '⭐ macOS·iOS 모두 적용',
        ],
    },

    'whatsapp': {
        'title': 'WhatsApp DB 분석',
        'icon': 'bi-whatsapp',
        'files': [
            '[Android] /data/data/com.whatsapp/databases/msgstore.db',
            '[Android] /sdcard/WhatsApp/Databases/msgstore.db.crypt15',
            '[iOS] App Domain: AppDomainGroup-group.net.whatsapp.WhatsApp.shared',
        ],
        'notes': [
            '평문 SQLite: SQLite format 3 시그니처',
            'crypt12/14/15: AES-256-GCM 암호화 (32B 키 필요)',
            '키 위치: /data/data/com.whatsapp/files/key (root 필요)',
            'crypt15는 32B end-to-end backup key 별도',
            '주요 테이블: messages, chat_list, contact, calls_log, media',
            'timestamp: Unix epoch ms',
            '디크립트 도구: github.com/MaxiHuHe04/Whatsapp-Crypt14-Decrypter',
        ],
    },

    'usb': {
        'title': 'USB 추적 핵심 경로',
        'icon': 'bi-usb-symbol',
        'sections': [
            {'name': '레지스트리', 'paths': [
                ('SYSTEM', 'ControlSet001\\Enum\\USBSTOR\\Disk&Ven_<X>&Prod_<Y>&Rev_<Z>\\<Serial>', '디스크 USB 상세'),
                ('SYSTEM', 'ControlSet001\\Enum\\USBSTOR\\Disk&Ven_<X>&Prod_<Y>&Rev_<Z>\\<Serial>\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\0064', '최초 연결 (FILETIME 8B)'),
                ('SYSTEM', 'ControlSet001\\Enum\\USBSTOR\\<...>\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\0066', '⭐ 마지막 연결'),
                ('SYSTEM', 'ControlSet001\\Enum\\USBSTOR\\<...>\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\0067', '⭐ 마지막 제거'),
                ('SYSTEM', 'MountedDevices', '드라이브 레터 ↔ USB 시리얼 매핑'),
                ('SOFTWARE', 'Microsoft\\Windows Portable Devices\\Devices', 'WPD 장치명'),
            ]},
            {'name': '파일시스템', 'paths': [
                ('Windows', 'C:\\Windows\\INF\\setupapi.dev.log', '⭐ USB 최초 연결 시각·드라이버 설치 텍스트 로그'),
                ('Windows', 'C:\\Windows\\inf\\setupapi.app.log', '앱 설치 로그 (보조)'),
            ]},
        ],
    },
}


# tool URL → registry hive 매핑 (도구별 자동 필터)
_TOOL_HIVE_MAP = {
    'registry': None,  # 전체
    'mft': ['파일시스템'],
    'sqlite': None,
    'amcache': ['Amcache.hve'],
    'lnk': None,
    'evtx': ['파일시스템'],
}


from flask import session
from monitor.views.tools import bp as _bp


@_bp.context_processor
def inject_tool_paths():
    """현재 도구의 관련 경로 정보 자동 주입"""
    path = (request.path or '').rstrip('/')
    if path.startswith('/tools/'):
        name = path[len('/tools/'):].split('/')[0]
        return {'current_tool_paths': _TOOL_RELATED_PATHS.get(name)}
    return {'current_tool_paths': None}


@bp.route('/forensic-paths')
def forensic_paths_tool():
    # 카테고리·하이브별 그룹화
    by_hive = {}
    for p in _FORENSIC_PATHS:
        by_hive.setdefault(p['hive'], []).append(p)
    by_os = {}
    for p in _FILESYSTEM_PATHS:
        by_os.setdefault(p['os'], []).append(p)
    return render_template('tools/forensic_paths.html',
                           reg_paths=_FORENSIC_PATHS,
                           fs_paths=_FILESYSTEM_PATHS,
                           by_hive=by_hive, by_os=by_os)


@bp.route('/beginner')
def beginner_tool():
    return render_template('tools/beginner.html',
                           scenarios=_BEGINNER_SCENARIOS)


@bp.route('/glossary')
def glossary_tool():
    return render_template('tools/glossary.html', glossary=_GLOSSARY)
